producto/urls.py
from django.urls import path
from . import views

producto_patterns = ([
                         path('producto/gestionar', views.ProductManage.as_view(), name='manage'),
                         path('producto/create/', views.ProductCreate.as_view(), name='create'),
                         path('producto/update/<int:pk>/', views.ProductUpdate.as_view(), name='update'),
                         path('producto/delete/<int:pk>/', views.ProductoDelete.as_view(), name='delete'),
                         path('categoria/gestionar', views.CategoriaList.as_view(), name='categoria_index'),
                         path('categoria/create/', views.CategoriaCreate.as_view(), name='categoria_create'),
                         path('categoria/update/<int:pk>/', views.CategoriaUpdate.as_view(), name='categoria_update'),
                         path('categoria/delete/<int:pk>/', views.CategoriaDelete.as_view(), name='categoria_delete'),
                     ], 'producto')

venta/urls.py
from django.urls import path
from . import views
from compra.views import *

venta_patterns = ([ 
                      path('', views.product_list, name='product_list'),
                      path('ventas/', views.VentaList.as_view(), name='ventas'),
                      path('compras/', views.compra, name='compra'), 
                      path('balance/', views.balance, name='balance'),   
                      path('ventasPorProducto/', views.dashboard, name='ventasPorProducto'),
                      path('ventas/detail/<int:pk>/', views.VentaDetail.as_view(), name='detail'),
                      path('ventas/anular/<int:pk>/', views.VentaUpdate.as_view(), name='anular'),
                      path('ventas/facturar/<int:pk>/', views.VentaFactura.as_view(), name='facturar'),
                      path('imprimir/<int:venta_id>/', views.imprimir_ticket, name='imprimir'),
                      path('imprimir_ticket/<int:venta_id>/', views.PrintTicketPDFView.as_view(), name='imprimir_ticket'),
                      path('carrito/', views.carrito, name='carrito'),
                  ], 'venta')

ventas/urls.py
from django.contrib import admin
from django.urls import path, include
from venta.views import login

from producto.urls import producto_patterns
from venta.urls import venta_patterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',login,name="login"),
    path('', include(venta_patterns)),
    path('', include(producto_patterns)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

producto/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator


# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

# Validador personalizado para el tamaño de la imagen
def validate_image_size(value):
    width, height = value.width, value.height
    if width != 500 or height != 500:
        raise ValidationError('La imagen debe ser de 500x500 píxeles.')


class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=200)
    imagen = models.ImageField(
        upload_to='img/',
        blank=True,
        null=True,
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), validate_image_size]
    )
    costo = models.DecimalField(verbose_name="Costo unit.",max_digits=25, decimal_places=2,default=0 ,blank=True,null=True)
    precio_usd = models.DecimalField(verbose_name="Costo en Dolares",default=0,max_digits=25, decimal_places=2,blank=True,null=True)
    precio = models.DecimalField(verbose_name="Precio Venta",default=0,max_digits=25, decimal_places=2)

    precio_bs = models.DecimalField(verbose_name="Bolivianos",default=0,max_digits=25, decimal_places=2)
    en_stock = models.DecimalField(max_digits=25, default=0, decimal_places=2)


    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.nombre + " " + self.descripcion

    def save(self, *args, **kwargs):
        super(Producto, self).save(*args, **kwargs)

producto/forms.py
from django import forms

from producto.models import Producto, Categoria


class ProductoForm(forms.ModelForm):
    nombre = forms.TextInput(attrs={'class': 'form-control'})
    descripcion = forms.TextInput(attrs={'class': 'form-control'})
    precio = forms.DecimalField(initial=00.00, min_value=0,
                                widget=forms.NumberInput(attrs={
                                    'class': 'form-control',
                                }))

    imagen = forms.ImageField(
        required=False,  # Permite que el campo sea opcional
        widget=forms.FileInput(attrs={'class': 'form-control-file'}),
    )
    categoria = forms.Select(attrs={'class': 'form-control'})

    class Meta:
        model = Producto
        fields = ['nombre', 'descripcion', 'imagen',  'precio', 'categoria']
        widgets = {
            'nombre': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Nombre del producto'
            }),
            'descripcion': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ejemplo: Caja x 24 Unid.. Etc'
            }),
            'categoria':forms.Select(attrs={
                'class': 'form-control'
            })
        }
        labels = {
            'nombre': 'Nombre',
            'descripcion': 'Envase',
            'imagen': 'Imagen del producto',
            'precio': 'Precio en Pesos',
            'categoria': 'Categoría',
        }


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = '__all__'
        widgets = {
            'nombre': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Nombre de la categoría'
            }),
        }

producto/views.py
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DeleteView, CreateView

from producto.forms import ProductoForm, CategoriaForm
from producto.models import Producto, Categoria

# Producto Views
from venta.models import Venta


class ProductManage(ListView):
    model = Producto
    template_name_suffix = '_manage'


class ProductCreate(CreateView):
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy('producto:manage')


class ProductUpdate(UpdateView):
    model = Producto
    form_class = ProductoForm
    template_name_suffix = '_update_form'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductUpdate, self).get_context_data(**kwargs)
        producto = Producto.objects.get(id=self.kwargs['pk'])
        if not producto:
            raise Http404
        else:
            # Añadimos al contexto el objeto del producto
            context['nombre'] = producto.nombre
        return context

    def get_success_url(self):
        return reverse_lazy('producto:manage')


class ProductoDelete(DeleteView):
    model = Producto
    success_url = reverse_lazy('producto:manage')


# Categoría Views

class CategoriaList(ListView):
    model = Categoria


class CategoriaCreate(CreateView):
    model = Categoria
    form_class = CategoriaForm
    success_url = reverse_lazy('producto:categoria_index')


class CategoriaUpdate(UpdateView):
    model = Categoria
    form_class = CategoriaForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('producto:categoria_index')


class CategoriaDelete(DeleteView):
    model = Categoria
    success_url = reverse_lazy('producto:categoria_index')

producto/templates/producto/categoria_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<div class="" style="text-align: start;">
    <h1 class="text-light p-3" style="margin-top: 70px;"><b></b></h1>
</div>
<div class="container">

 
    <div class="row mt-3">
        <div class="col-md-9 mx-auto">
            <div>
                <h1>{{ object.nombre }}</h1>
                <form action="" method="post">{% csrf_token %}
                    <p>¿Estás seguro de que quiere borrar esta categoría?</p>
                    <input class="btn btn-danger btn-block" type="submit" value="Sí, borrar el categoría"/>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

producto/templates/producto/categoria_form.html
{% extends 'core/base.html' %}
{% block title %}
    Crear categoría
{% endblock %}
{% block content %}
    <div class="mt-3 mb-3">
        <h2 class="section-heading mb-2">Creando categoría</h2>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="text-center">
                <input class="btn btn-primary btn-block" type="submit" value="Crear categoría"/>
                <br/>
            </div>
        </form>
    </div>
{% endblock %}

producto/templates/producto/categoria_list.html
{% extends 'core/base.html' %}
{% block title %}
    Gestionar Categorías
{% endblock %}
{% block content %}
    <div class="d-flex justify-content-between mb-4 mt-4">
        <h1 class="">Lista de categorías</h1>
        <div class="mt-2">
            <a href="{% url 'producto:categoria_create' %}" class="btn btn-primary">Crear</a>
        </div>
    </div>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Opciones</th>
        </tr>
        </thead>
        <tbody>
        {% for categoria in categoria_list %}
            <tr>
                <td scope="row">{{ categoria.id }}</td>
                <td>{{ categoria.nombre }}</td>
                <td>
                    <a class="btn btn-primary"
                       href="{% url 'producto:categoria_update' categoria.id %}">Editar</a>
                    <a class="btn btn-danger"
                       href="{% url 'producto:categoria_delete' categoria.id %}">Eliminar</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

producto/templates/producto/categoria_update_form.html
{% extends 'core/base.html' %}
{% block content %}

<div class="container">
    <div class="" style="text-align: start;">
        <h1 class="text-light p-3" style="margin-top: 100px;"><b>Actualizar producto</b></h1>
    </div>
    
    <div class="card p-3">
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="text-center">
                    <input class="btn btn-primary btn-block" type="submit" value="Crear producto"/>
                    <a href="/producto/gestionar"><input class="btn btn-danger btn-block" type="button" value="Volver"/></a>
                    <br/>
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}        

producto/templates/producto/producto_confirm_delete.html
{% extends 'core/base.html' %}
{% block content %}

<div class="container" style="min-height: 90vh;">
    <div class="" style="text-align: start;">
        <h1 class="text-light p-3" style="margin-top: 100px;"><b>Actualizar producto</b></h1>
    </div>
    
    <div class="card p-3 text-dark">
        <div class="card-body">
            <h1 class="text-danger">{{ object.nombre }}</h1>
            <p>Descripción: <span>{{ object.descripción }}</span></p>
            <p>En stock: <span>{{ object.en_stock }}</span></p>
            <p>Precio: <span>{{ object.precio }}</span></p>
            <p>Categoría: <span>{{ object.categoria }}</span></p>
            <form action="" method="post">{% csrf_token %}
                <p>¿Estás seguro de que quiere borrar este producto?</p>
                <input class="btn btn-primary btn-block" type="submit" value="Sí, borrar el producto"/>
                <a href="/producto/gestionar"><input class="btn btn-danger btn-block" type="button" value="Volver"/></a>
            </form>
        </div>
    </div>
</div>
{% endblock %}        

producto/templates/producto/producto_form.html
{% extends 'core/base.html' %}
{% block content %}
<style>
    label {
    font-size: large;
    font-weight: bold;
    
}
</style>
<div class="container">
    <div class="" style="text-align: start;">
        <h1 class="text-light p-3" style="margin-top: 100px;"><b>Nuevo producto</b></h1>
    </div>
    
    <div class="card p-3">
        <div class="card-body">
            <form action="" method="post" class="text-primary" style="text-align: left;">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="text-center">
                    <input class="btn btn-primary btn-block" type="submit" value="Crear producto"/>
                    <a href="/producto/gestionar"><input class="btn btn-danger btn-block" type="button" value="Volver"/></a>
                    <br/>
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}        

producto/templates/producto/producto_manage.html
{% extends 'core/base.html' %}
{% block title %}
    Gestionar Productos
{% endblock %}
{% block content %}
<!-- jQuery CDN -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-oC7cv2T8pA2dELiO4K6q6JvC6K4NJd/b9F2Jk2FZuZM=" crossorigin="anonymous"></script>

<div class="container">
    <div class="" style="text-align: start;">
        <h1 class="text-light p-3" style="margin-top: 70px;"><b></b></h1>
    </div>
    
    <div class="card p-3">
        <!--<div class="mt-2 d-flex">
            <button class="btn btn-primary" data-toggle="" data-target="/producto/create" >
                <b style="font-size: large;"><a href="/producto/create" style="color: aliceblue;text-decoration: none;">Nuevo Producto</a></b>
            </button>
        </div>-->
        <div class="mt-2 d-flex">
            <h3 class="text-primary p-2">Listado de Productos</h3>
        </div>
        
        <hr class="text-secondary" style="height: 15px;">
        <table class="table table-hover">
            <thead>
            <tr>
                <!--<th scope="col">#</th>-->
                <th scope="col">Nombre</th>
                <th scope="col">Envase</th>
                <th scope="col">En stock</th>
                <th scope="col">Categoría</th>
                <th scope="col">Precio $</th>
                <!--<th scope="col">Opciones</th>-->
            </tr>
            </thead>
            <tbody>
            {% for producto in producto_list %}
                <tr>
                    <!--<td scope="row">{{ producto.id }}</td>-->
                    <td>{{ producto.nombre }}</td>
                    <td>{{ producto.descripcion|truncatechars:100 }}</td>

                    {% if producto.en_stock >= 0 %}
                    <td><b class="text-success">{{ producto.en_stock|floatformat:0 }}</b></td>
                    {% else %}
                    <td><b class="text-danger">{{ producto.en_stock|floatformat:0 }}</b></td>
                    {% endif %}
                    <td>{{ producto.categoria|default:'Sin Categoría' }}</td>
                    <td>$ {{ producto.precio }}</td>
                   <!--   <td>
                      <a class="btn btn-primary"
                        href="{% url 'producto:update' producto.id %}">Editar</a>
                      <a class="btn btn-danger"
                        href="{% url 'producto:delete' producto.id %}">Eliminar</a>
                    </td>-->
                </tr>
            {% endfor %}
            </tbody>
        </table>
</div>
</div>

{% endblock %}

producto/templates/producto/producto_update_form.html
{% extends 'core/base.html' %}
{% block content %}

<div class="container">
    <div class="" style="text-align: start;">
        <h1 class="text-light p-3" style="margin-top: 100px;"><b>Actualizar producto</b></h1>
    </div>
    
    <div class="card p-3">
        <div class="card-body text-secondary">
            <h2 class="section-heading mb-2 text-danger">Actualizando producto</h2>
            <p class="h5">Usted está actualizando: {{ nombre }}</p>
            <form action="" method="post" style="text-align: left;">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="text-center">
                    <input class="btn btn-primary btn-block" type="submit" value="Actualizar producto"/>
                    <a href="/producto/gestionar"><input class="btn btn-danger btn-block" type="button" value="Volver"/></a>
                    <br/>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}        